import HilbertUMD.UMD.UMDSimpleTerminal
import Mathlib.MeasureTheory.Function.LpSeminorm.Trim

/-! Approximation of finite martingales by filtrations generated by finitely
many events. All conditional expectations are taken with the original measure. -/

noncomputable section
open MeasureTheory Filter
open scoped ENNReal NNReal

namespace HilbertUMD

/-- A sigma algebra generated by finitely many events. -/
def FinitelyGeneratedSigma {Ω : Type*} (s : MeasurableSpace Ω) : Prop :=
  ∃ a : Set (Set Ω), a.Finite ∧ s = MeasurableSpace.generateFrom a

namespace FiniteFiltrationApproximation

variable {Ω E : Type*}

def fibers (f : Ω → E) : Set (Set Ω) :=
  (fun x => f ⁻¹' {x}) '' Set.range f

theorem fibers_finite {f : Ω → E} (hf : (Set.range f).Finite) : (fibers f).Finite :=
  hf.image _

theorem measurable_fiber_generate (f : Ω → E) (x : E) :
    MeasurableSet[MeasurableSpace.generateFrom (fibers f)] (f ⁻¹' {x}) := by
  by_cases hx : x ∈ Set.range f
  · exact MeasurableSpace.measurableSet_generateFrom ⟨x, hx, rfl⟩
  · have he : f ⁻¹' {x} = ∅ := by
      ext a
      simp only [Set.mem_preimage, Set.mem_singleton_iff, Set.mem_empty_iff_false, iff_false]
      exact fun h => hx ⟨a, h⟩
    rw [he]
    exact @MeasurableSet.empty Ω (MeasurableSpace.generateFrom (fibers f))

variable {m : ℕ} [mΩ : MeasurableSpace Ω]
  (ℱ : Filtration (Fin (m + 1)) mΩ)
  (f : Fin (m + 1) → Ω → E)

def prefixEvents (k : Fin (m + 1)) : Set (Set Ω) :=
  ⋃ j ∈ Set.Iic k, fibers (f j)

omit mΩ in
theorem prefixEvents_finite (hf : ∀ k, (Set.range (f k)).Finite) (k : Fin (m + 1)) :
    (prefixEvents f k).Finite :=
  (Set.toFinite (Set.Iic k)).biUnion fun j _ => fibers_finite (hf j)

variable (hmf : ∀ k x, MeasurableSet[ℱ k] ((f k) ⁻¹' {x}))

def filtration : Filtration (Fin (m + 1)) mΩ where
  seq k := MeasurableSpace.generateFrom (prefixEvents f k)
  mono' := by
    intro i j hij
    apply MeasurableSpace.generateFrom_mono
    exact Set.biUnion_mono (Set.Iic_subset_Iic.mpr hij) (fun _ _ => Set.Subset.rfl)
  le' := by
    intro k
    apply MeasurableSpace.generateFrom_le
    rintro s hs
    obtain ⟨j, hj⟩ := Set.mem_iUnion.mp hs
    obtain ⟨hjk, x, hx, rfl⟩ := Set.mem_iUnion.mp hj
    exact ℱ.le k _ (ℱ.mono hjk _ (hmf j x))

theorem filtration_finite (hf : ∀ k, (Set.range (f k)).Finite) (k : Fin (m + 1)) :
    FinitelyGeneratedSigma (filtration ℱ f hmf k) :=
  ⟨prefixEvents f k, prefixEvents_finite f hf k, rfl⟩

theorem filtration_le (k : Fin (m + 1)) : filtration ℱ f hmf k ≤ ℱ k := by
  apply MeasurableSpace.generateFrom_le
  rintro s hs
  obtain ⟨j, hj⟩ := Set.mem_iUnion.mp hs
  obtain ⟨hjk, x, hx, rfl⟩ := Set.mem_iUnion.mp hj
  exact ℱ.mono hjk _ (hmf j x)

variable [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]

omit [NormedSpace ℝ E] [CompleteSpace E] in
theorem stronglyMeasurable_approx (hf : ∀ k, (Set.range (f k)).Finite) (k : Fin (m + 1)) :
    StronglyMeasurable[filtration ℱ f hmf k] (f k) := by
  have hle : MeasurableSpace.generateFrom (fibers (f k)) ≤ filtration ℱ f hmf k := by
    apply MeasurableSpace.generateFrom_mono
    intro s hs
    exact Set.mem_iUnion.mpr ⟨k, Set.mem_iUnion.mpr ⟨Set.mem_Iic.mpr le_rfl, hs⟩⟩
  let : MeasurableSpace Ω := MeasurableSpace.generateFrom (fibers (f k))
  let sf : @SimpleFunc Ω (MeasurableSpace.generateFrom (fibers (f k))) E :=
    ⟨f k, measurable_fiber_generate _ , hf k⟩
  exact sf.stronglyMeasurable.mono hle

end FiniteFiltrationApproximation

namespace UMDTerminal

variable {Ω E : Type*} {s t : MeasurableSpace Ω} [mΩ : MeasurableSpace Ω]
  [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
  (μ : Measure Ω) [IsFiniteMeasure μ]

theorem conditionalL2_tower (hst : s ≤ t) (ht : t ≤ mΩ) (g : Lp E 2 μ) :
    conditionalL2 μ s (conditionalL2 μ t g) = conditionalL2 μ s g := by
  apply Lp.ext
  exact (conditionalL2_ae_eq μ s _).trans
    ((condExp_congr_ae (conditionalL2_ae_eq μ t g)).trans
      ((condExp_condExp_of_le hst ht).trans (conditionalL2_ae_eq μ s g).symm))

theorem conditionalL2_fixed (hs : s ≤ mΩ) {f : Ω → E}
    (hf : MemLp f 2 μ) (hfs : StronglyMeasurable[s] f) :
    conditionalL2 μ s (hf.toLp f) = hf.toLp f := by
  apply Lp.ext
  refine (conditionalL2_ae_eq μ s _).trans
    ((condExp_congr_ae hf.coeFn_toLp).trans ?_)
  rw [condExp_of_stronglyMeasurable hs hfs (hf.integrable (by norm_num))]
  exact hf.coeFn_toLp.symm

theorem conditionalL2_dist_le (hst : s ≤ t) (ht : t ≤ mΩ)
    (g v : Lp E 2 μ) (hv : conditionalL2 μ s v = v) :
    dist (conditionalL2 μ s g) (conditionalL2 μ t g) ≤
      2 * dist v (conditionalL2 μ t g) := by
  calc
    _ ≤ dist (conditionalL2 μ s g) v + dist v (conditionalL2 μ t g) := dist_triangle _ _ _
    _ = dist (conditionalL2 μ s (conditionalL2 μ t g)) (conditionalL2 μ s v) +
        dist v (conditionalL2 μ t g) := by rw [conditionalL2_tower μ hst ht, hv]
    _ ≤ dist (conditionalL2 μ t g) v + dist v (conditionalL2 μ t g) := by
      apply add_le_add _ le_rfl
      simpa using (conditionalL2_lipschitz μ s).dist_le_mul (conditionalL2 μ t g) v
    _ = _ := by rw [dist_comm (conditionalL2 μ t g) v]; ring

omit [IsFiniteMeasure μ] in
theorem exists_simple_near_conditionalL2 (hs : s ≤ mΩ) (g : Lp E 2 μ)
    {δ : ℝ} (hδ : 0 < δ) :
    ∃ (f : Ω → E), (Set.range f).Finite ∧
      (∀ x, MeasurableSet[s] (f ⁻¹' {x})) ∧
      ∃ hf : MemLp f 2 μ, dist (hf.toLp f) (conditionalL2 μ s g) < δ := by
  let a : Ω → E := μ[g | s]
  have ha : StronglyMeasurable[s] a := stronglyMeasurable_condExp
  have halp : MemLp a 2 μ := (Lp.memLp g).condExp (by norm_num)
  have happrox : ∃ f : @SimpleFunc Ω s E,
      eLpNorm (a - @SimpleFunc.toFun Ω s E f) 2 (μ.trim hs) < ENNReal.ofReal δ ∧
        MemLp (@SimpleFunc.toFun Ω s E f) 2 (μ.trim hs) := by
    let : MeasurableSpace Ω := s
    have hatrim : MemLp a 2 (μ.trim hs) := ⟨ha.aestronglyMeasurable, by
      rw [eLpNorm_trim hs ha]
      exact halp.2⟩
    exact hatrim.exists_simpleFunc_eLpNorm_sub_lt (by norm_num)
      (ne_of_gt (ENNReal.ofReal_pos.mpr hδ))
  obtain ⟨f, hdist, hftrim⟩ := happrox
  have hf := memLp_of_memLp_trim hs hftrim
  refine ⟨@SimpleFunc.toFun Ω s E f, @SimpleFunc.finite_range' Ω s E f,
    @SimpleFunc.measurableSet_fiber' Ω s E f, hf, ?_⟩
  rw [dist_comm, dist_edist, conditionalL2, Lp.edist_toLp_toLp]
  apply ENNReal.toReal_lt_of_lt_ofReal
  have hfm : StronglyMeasurable[s] (@SimpleFunc.toFun Ω s E f) := by
    let : MeasurableSpace Ω := s
    exact f.stronglyMeasurable
  change eLpNorm (a - @SimpleFunc.toFun Ω s E f) 2 μ < ENNReal.ofReal δ
  rw [← eLpNorm_trim hs (ha.sub hfm)]
  exact hdist

theorem exists_finiteFiltration_near {m : ℕ}
    (ℱ : Filtration (Fin (m + 1)) mΩ) (g : Lp E 2 μ)
    {δ : ℝ} (hδ : 0 < δ) :
    ∃ 𝒢 : Filtration (Fin (m + 1)) mΩ,
      (∀ k, FinitelyGeneratedSigma (𝒢 k)) ∧
      ∀ k, dist (conditionalL2 μ (𝒢 k) g) (conditionalL2 μ (ℱ k) g) < δ := by
  choose f hfin hmeas hmem hdist using
    (fun k : Fin (m + 1) => exists_simple_near_conditionalL2 μ (ℱ.le k) g
      (half_pos hδ))
  let 𝒢 := FiniteFiltrationApproximation.filtration ℱ f hmeas
  refine ⟨𝒢, FiniteFiltrationApproximation.filtration_finite ℱ f hmeas hfin, ?_⟩
  intro k
  have hfix := conditionalL2_fixed μ (𝒢.le k) (hmem k)
    (FiniteFiltrationApproximation.stronglyMeasurable_approx ℱ f hmeas hfin k)
  have hb := conditionalL2_dist_le μ
    (FiniteFiltrationApproximation.filtration_le ℱ f hmeas k)
    (ℱ.le k) g ((hmem k).toLp (f k)) hfix
  exact hb.trans_lt (by linarith [hdist k])

variable {𝕜 F : Type*} [RCLike 𝕜] [NormedSpace 𝕜 E]
  [NormedAddCommGroup F] [NormedSpace 𝕜 F]

def valuesTransformL2 {m : ℕ} (T : E →L[𝕜] F) (ε : Fin m → 𝕜)
    (v : Fin (m + 1) → Lp E 2 μ) : Lp F 2 μ :=
  ∑ k : Fin m, ε k • (T.compLpL 2 μ) (v k.succ - v k.castSucc)

omit [IsFiniteMeasure μ] [NormedSpace ℝ E] [CompleteSpace E] in
theorem valuesTransformL2_continuous {m : ℕ} (T : E →L[𝕜] F) (ε : Fin m → 𝕜) :
    Continuous (valuesTransformL2 μ T ε) := by
  apply continuous_finsetSum
  intro k _
  exact ((T.compLpL 2 μ).continuous.comp
    ((continuous_apply k.succ).sub (continuous_apply k.castSucc))).const_smul (ε k)

def processValuesL2 {m : ℕ} (ℱ : Filtration (Fin (m + 1)) mΩ)
    (g : Lp E 2 μ) : Fin (m + 1) → Lp E 2 μ :=
  fun k => conditionalL2 μ (ℱ k) g

omit [IsFiniteMeasure μ] in
theorem valuesTransformL2_process {m : ℕ} (ℱ : Filtration (Fin (m + 1)) mΩ)
    (T : E →L[𝕜] F) (ε : Fin m → 𝕜) (g : Lp E 2 μ) :
    valuesTransformL2 μ T ε (processValuesL2 μ ℱ g) = transformL2 μ ℱ T ε g := rfl

def finiteProcessesL2 (m : ℕ) (g : Lp E 2 μ) : Set (Fin (m + 1) → Lp E 2 μ) :=
  {v | ∃ 𝒢 : Filtration (Fin (m + 1)) mΩ,
    (∀ k, FinitelyGeneratedSigma (𝒢 k)) ∧ v = processValuesL2 μ 𝒢 g}

theorem processValuesL2_mem_closure {m : ℕ} (ℱ : Filtration (Fin (m + 1)) mΩ)
    (g : Lp E 2 μ) : processValuesL2 μ ℱ g ∈ closure (finiteProcessesL2 μ m g) := by
  apply Metric.mem_closure_iff.mpr
  intro δ hδ
  obtain ⟨𝒢, h𝒢, hdist⟩ := exists_finiteFiltration_near μ ℱ g hδ
  refine ⟨processValuesL2 μ 𝒢 g, ⟨𝒢, h𝒢, rfl⟩, ?_⟩
  rw [dist_pi_lt_iff hδ]
  intro k
  rw [dist_comm]
  exact hdist k

/-- The transform inequality passes from finite sub-filtrations to the given
filtration by simultaneous L2 approximation. -/
theorem bound_of_finiteFiltrations {m : ℕ}
    (ℱ : Filtration (Fin (m + 1)) mΩ) (T : E →L[𝕜] F) (ε : Fin m → 𝕜)
    (g : Lp E 2 μ) (C : ℝ≥0)
    (h : ∀ 𝒢 : Filtration (Fin (m + 1)) mΩ,
      (∀ k, FinitelyGeneratedSigma (𝒢 k)) →
      ‖transformL2 μ 𝒢 T ε g‖ ≤ (C : ℝ) * ‖g‖) :
    ‖transformL2 μ ℱ T ε g‖ ≤ (C : ℝ) * ‖g‖ := by
  let S : Set (Fin (m + 1) → Lp E 2 μ) :=
    {v | ‖valuesTransformL2 μ T ε v‖ ≤ (C : ℝ) * ‖g‖}
  have hclosed : IsClosed S :=
    isClosed_le (valuesTransformL2_continuous μ T ε).norm continuous_const
  have hsub : finiteProcessesL2 μ m g ⊆ S := by
    rintro v ⟨𝒢, h𝒢, rfl⟩
    change ‖valuesTransformL2 μ T ε (processValuesL2 μ 𝒢 g)‖ ≤ _
    rw [valuesTransformL2_process]
    exact h 𝒢 h𝒢
  have hx := (closure_minimal hsub hclosed) (processValuesL2_mem_closure μ ℱ g)
  change ‖valuesTransformL2 μ T ε (processValuesL2 μ ℱ g)‖ ≤ _ at hx
  rwa [valuesTransformL2_process] at hx

end UMDTerminal

universe uΩ

variable {𝕜 E F : Type*} [RCLike 𝕜]
  [NormedAddCommGroup E] [NormedSpace ℝ E] [NormedSpace 𝕜 E] [CompleteSpace E]
  [NormedAddCommGroup F] [NormedSpace 𝕜 F]

/-- Terminal tests whose filtration is generated by finitely many events. -/
def ProbabilityFiniteTerminalBound (T : E →L[𝕜] F) (C : ℝ≥0) : Prop :=
  ∀ (Ω : Type uΩ) (mΩ : MeasurableSpace Ω) (μ : Measure Ω), IsProbabilityMeasure μ →
  ∀ (m : ℕ), 1 ≤ m →
  ∀ (ℱ : Filtration (Fin (m + 1)) mΩ), (∀ k, FinitelyGeneratedSigma (ℱ k)) →
  ∀ (g : SimpleFunc Ω E) (ε : Fin m → 𝕜), (∀ k, ‖ε k‖ = 1) →
    eLpNorm (martingaleTransform T ε (fun k => μ[g | ℱ k])) 2 μ ≤
      (C : ℝ≥0∞) * eLpNorm g 2 μ

theorem probabilitySimpleTerminalBound_of_finite {T : E →L[𝕜] F} {C : ℝ≥0}
    (h : ProbabilityFiniteTerminalBound.{uΩ} T C) :
    ProbabilitySimpleTerminalBound.{uΩ} T C := by
  intro Ω mΩ μ hμ m hm ℱ g ε hε
  have hg := g.memLp_of_isFiniteMeasure 2 μ
  have hb := UMDTerminal.bound_of_finiteFiltrations μ ℱ T ε (hg.toLp g) C (by
    intro 𝒢 h𝒢
    rw [Lp.norm_def,
      eLpNorm_congr_ae (UMDTerminal.transformL2_toLp_ae_eq μ 𝒢 T ε hg), Lp.norm_toLp]
    have hb := ENNReal.toReal_mono
      (ENNReal.mul_ne_top ENNReal.coe_ne_top hg.eLpNorm_ne_top)
      (h Ω mΩ μ hμ m hm 𝒢 h𝒢 g ε hε)
    simpa only [ENNReal.toReal_mul, ENNReal.coe_toReal] using hb)
  have hh := ENNReal.ofReal_le_ofReal hb
  simpa only [ENNReal.ofReal_mul C.coe_nonneg, ENNReal.ofReal_coe_nnreal, ofReal_norm,
    Lp.enorm_def, eLpNorm_congr_ae (UMDTerminal.transformL2_toLp_ae_eq μ ℱ T ε hg),
    eLpNorm_congr_ae hg.coeFn_toLp] using hh

theorem umdBound_of_probabilityFiniteTerminalBound {T : E →L[𝕜] F} {C : ℝ≥0}
    (h : ProbabilityFiniteTerminalBound.{uΩ} T C) : UMDBound.{uΩ} 2 T C :=
  umdBound_of_probabilitySimpleTerminalBound (probabilitySimpleTerminalBound_of_finite h)

end HilbertUMD
